name: Keep Supabase Active

on:
  schedule:
    # Run every day at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Supabase Database
        run: |
          echo "Pinging Supabase to keep database active..."
          
          # Try production URL first, fallback to preview if needed
          URLS=(
            "https://blossom.edu.mm/api/slider"
            "https://bloossom-private-school.vercel.app/api/slider"
          )
          
          for url in "${URLS[@]}"; do
            echo "Trying: $url"
            if curl -f -s --max-time 30 "$url" > /dev/null 2>&1; then
              echo "✅ Successfully pinged: $url"
              echo "Database kept active at $(date)"
              exit 0
            else
              echo "⚠️ Failed to reach: $url"
            fi
          done
          
          echo "❌ All URLs failed - please check deployment"
          exit 1

      - name: Log Result
        if: always()
        run: |
          echo "Keep-alive job completed at $(date)"
          echo "Next run scheduled for tomorrow at 2 AM UTC"
